competition/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
import competition.views

app_name='competition'

urlpatterns = [
    url(r'^$', competition.views.home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='competition/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', competition.views.RegisterView.as_view(), name='register'),
    url(r'^search/$', competition.views.TournamentSearchListView.as_view(), name='search'),
    url(r'^my_leagues/$', competition.views.my_leagues, name='users_leagues'),
]

football/urls.py
import football.views
from django.conf.urls import include, url
from rest_framework import routers
from football import view_sets

app_name = 'football'

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', view_sets.UserViewSet)
router.register(r'tournaments', view_sets.TournamentViewSet)
router.register(r'tie_breakers', view_sets.TieBreakerViewSet)
router.register(r'playoffs', view_sets.PlayoffViewSet)
router.register(r'rounds', view_sets.RoundViewSet)
router.register(r'playoffround', view_sets.PlayoffRoundViewSet)
router.register(r'players', view_sets.PlayerViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^addResult/(?P<match_id>[0-9]+)/$', football.views.add_result, name='add_result'),
    url(r'^addPlayoffResult/(?P<round_id>[0-9]+)/$', football.views.add_playoff_result, name='add_playoff_result'),
    url(r'^completeGroup/(?P<group_id>[0-9]+)/$', football.views.complete_group, name='complete_group'),
    url(r'^createLeague/$', football.views.AddLeague.as_view(), name='create_league'),
    url(r'^tournament/(?P<tournament_id>[A-Za-z0-9]+)/$', football.views.tournament, name='tournament'),
    url(r'^test/$', football.views.test, name='tournament'),
    url(r'^rest/', include(router.urls))
]

leaguegenerator/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from leaguegenerator.view_sets import UserViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^football/', include('football.urls')),
    url(r'^', include('competition.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^rest/', include(router.urls))
]

competition/models.py
from django.db import models
from model_utils.managers import InheritanceManager
from competition import util
from django.contrib.auth.models import User


class TieBreaker(models.Model):
    objects = InheritanceManager()
    name = models.CharField(max_length=200, db_index=True, unique=True)
    type = models.CharField(max_length=5, db_index=True, unique=True)

    def __str__(self):
        return self.name


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    display_name = models.CharField(max_length=200, unique=True)
    friends = models.ManyToManyField("self")

    def get_display_name(self):
        return self.display_name or self.user.username

    def __str__(self):
        return self.get_display_name()

class Tournament(models.Model):
    FOOTBALL = 'FOOT'
    TOURNAMENT_TYPES = (
        (FOOTBALL, 'Football'),
    )
    name = models.CharField(max_length=200, unique=True)
    tie_breakers = models.ManyToManyField(TieBreaker, through='TieBreakerOrder')
    type = models.CharField(max_length=4, choices=TOURNAMENT_TYPES)
    ext_id = models.CharField(max_length=10, unique=True)
    winners = models.ManyToManyField(Player)
    protected = models.BooleanField(default=False)
    unlisted = models.BooleanField(default=False)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.ext_id:
            self.ext_id = util.generate_id(10)
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    def __str__(self):
        return '{0}({1})'.format(self.name, self.ext_id)

    @staticmethod
    def visible():
        return Tournament.objects.filter(unlisted=False)


class TournamentPermissions(models.Model):

    READ = 'R'
    READ_WRITE = 'R/W'
    PERMISSION_TYPES = (
        (READ, 'Read'),
        (READ_WRITE, 'Read/Write'),
    )
    access = models.CharField(max_length=4, choices=PERMISSION_TYPES)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("tournament", "user")


class TieBreakerOrder(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    tie_breaker = models.ForeignKey(TieBreaker, on_delete=models.CASCADE)
    order = models.IntegerField()

    class Meta:
        ordering = ['order']
        unique_together = (("tournament", "order"), ("tie_breaker", "tournament"),)


class Rule(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    key = models.CharField(max_length=40)
    value = models.CharField(max_length=100)


    def __str__(self):
        return str(self.tournament) + ': ' + str(self.key) + ' = ' + str(self.value)

    class Meta:
        unique_together = ("tournament", "key")


class Match(models.Model):
    competitors = models.ManyToManyField(Player, through='MatchData')
    type = models.CharField(max_length=4, choices=Tournament.TOURNAMENT_TYPES)

    def __str__(self):
        return ' - '.join(x.get_display_name() for x in self.competitors.all())


MATCH_PLACEMENT = (
    ('H', 'Home'),
    ('A', 'Away'),
    ('N', 'Neutral'),
)


class MatchData(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    placement = models.CharField(max_length=1, choices=MATCH_PLACEMENT)


class Stage(models.Model):
    type = models.CharField(max_length=20, db_index=True, unique=True)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.type

    class Meta:
        ordering = ['order']


class Round(models.Model):
    """Represents group stage, qtr final, semi final and so on"""
    name = models.CharField(max_length=200)
    competitors = models.ManyToManyField(Player, blank=True)
    matches = models.ManyToManyField(Match, blank=True, through='MatchOrder')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE)

    def __str__(self):
        return '{0}: {1}'.format(str(self.tournament), self.name)

    class Meta:
        ordering = ['name']
        unique_together = ('name', 'tournament')


class MatchOrder(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    match = models.OneToOneField(Match, on_delete=models.CASCADE)
    order = models.IntegerField()

    def __str__(self):
        return '{0}, {1}'.format(str(self.round), str(self.match))

    class Meta:
        ordering = ['order']
        unique_together = (('round', 'order'), ('match',))


class Playoff(models.Model):
    objects = InheritanceManager()

    tournament = models.OneToOneField(Tournament, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.tournament)


class PlayoffRound(Round):
    """Used to point to the next round for the teams in this round, should be blank for the final"""
    next = models.ForeignKey('PlayoffRound', blank=True, null=True, on_delete=models.CASCADE)
    playoff = models.ForeignKey(Playoff, on_delete=models.CASCADE)


class Result(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()

    def __str__(self):
        return str(self.player) + " " + str(self.score)

    class Meta:
        unique_together = (("match", "player"),)


class News(models.Model):
    publish_date = models.DateTimeField()
    headline = models.TextField()
    text = models.TextField()
    link = models.TextField(blank=True)
    # News about a special player, if blank the news is general
    owner = models.ForeignKey(Player, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-publish_date']


class NewsData(models.Model):
    key = models.CharField(max_length=20)
    value = models.TextField()
    news = models.ForeignKey(News, on_delete=models.CASCADE)

competition/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms.fields import EmailField
from django.contrib.auth.models import User
from django.db import transaction
from django.utils.translation import gettext as _

from competition.models import Player


class MyUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    def _post_clean(self):
        super()._post_clean()
        try:
            Player.objects.get(display_name=self.cleaned_data['username'])
        except Player.DoesNotExist:
            return
        self.add_error('username', _('Taken username'))

    @transaction.atomic
    def save(self, commit=True):
        instance = super(MyUserCreationForm, self).save(commit=False)
        instance.player = Player(display_name=instance.username)
        if commit:
            instance.save()
            instance.player.save()
        return instance

    class Meta:
        model = User
        fields = ("username", "email")
        field_classes = {'username': UsernameField, 'email':EmailField}

competition/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.shortcuts import render, reverse
from django.views.generic import ListView, FormView

from competition.forms import MyUserCreationForm
from competition.models import Tournament, Player, News
from competition.util import TranslatedNews


def home(request):
    news = News.objects.all()[:3]
    context = {
        'news_list': [TranslatedNews(n) for n in news]
    }
    return render(request, 'competition/home.html', context=context)

@login_required
def my_leagues(request):
    try:
        player = Player.objects.get(user=request.user)
        tournaments = Tournament.objects.filter(round__competitors=player).distinct()
    except Player.DoesNotExist:
        tournaments = []
    context = {
        'object_list': sorted(tournaments, key= lambda x: x.name.lower())
    }
    return render(request, 'competition/tournament_list.html', context=context)


class RegisterView(FormView):

    def get_form_class(self):
        return MyUserCreationForm

    def get_template_names(self):
        return ['competition/register.html']

    def form_valid(self, form):
        username = form.cleaned_data['username']
        form.save()
        user = User.objects.get(username=username)
        login(self.request, user)
        return HttpResponseRedirect(reverse('competition:home'))


class TournamentSearchListView(ListView):
    model = Tournament
    paginate_by = 10

    def get_queryset(self):

        keywords = self.request.GET.get('q')
        tournaments = Tournament.visible()
        if self.request.user.is_authenticated:
            user = self.request.user
            player = Player.objects.get(user=user)
            tournaments = tournaments.filter(Q(protected=False) | Q(round__competitors=player))
        else:
            tournaments = tournaments.filter(protected=False)

        if keywords:
            return tournaments.annotate(search=SearchVector('ext_id', 'name')).filter(search=keywords).order_by('type', 'name').distinct()

        return Tournament.objects.none()

competition/templates/competition/home.html
{% extends 'competition/template.html' %}
{% load i18n %}


{% block extra_head %}
<style>
    body {
        padding-top: 0;
    }
</style>
{% endblock %}
{% block content %}


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">{% trans 'Welcome to the league generator' %}</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            {% for news in news_list %}
                <div class="col-md-4">
                    <h2>{{ news.headline }}</h2>
                    <p>{{ news.text }}</p>
                    {% if news.news.link %}
                        <p><a class="btn btn-secondary" href="{{ news.news.link }}" role="button">View details &raquo;</a></p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <hr>

    </div> <!-- /container -->

{% endblock %}

competition/templates/competition/login.html
{% extends 'competition/template.html' %}
{% load i18n %}
{% load static %}

{% block extra_head %}
    <style>
        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: 400;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
{% endblock %}
{% block content %}
    <form class="needs-validation" class="form-signin" method="post" novalidate>
        {% csrf_token %}
        <h2 class="form-signin-heading">{% trans 'Login' %}</h2>
        <div>
            <label for="username" class="sr-only">{% trans 'Username' %}</label>
            <input type="text" id="username" name="username" class="form-control rounded" placeholder="{% trans 'Username' %}" required autofocus>
            <div class="invalid-feedback">
                {% trans "Missing username" %}
            </div>
        </div>
        <div>
            <label for="inputPassword" class="sr-only">{% trans 'Password' %}</label>
            <input type="password" id="inputPassword" name="password" class="form-control rounded mt-2" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% trans "Missing password" %}
            </div>
        </div>
        <input type="hidden" name="next" value="{{ next }}">
        <div class="invalid-feedback" {% if form.errors %}style="display: block" {% endif %}>
            <label>{% trans 'Invalid credentials' %}</label>
        </div>
        <span class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> {% trans 'Remember me' %}
            </label>
        </span>
        <span class="float-right">
            <a href="{% url 'competition:register' %}">{% trans "Register" %}</a>
        </span>
        <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Sign in' %}</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'competition/formValidation.js' %}"></script>
{% endblock %}

competition/templates/competition/register.html
{% extends 'competition/template.html' %}
{% load i18n %}
{% load static %}

{% block extra_head %}
    <style>
        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin {
            margin-bottom: 10px;
        }
        .form-signin {
            font-weight: 400;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
{% endblock %}
{% block content %}
    <form class="needs-validation" class="form-signin" method="post" novalidate>
        {% csrf_token %}
        <h2 class="form-signin-heading">{% trans 'Welcome!' %}</h2>
        <div class="my-2">
            <label for="username">{% trans 'Username' %}</label>
            <input type="text" id="username" name="username" class="form-control rounded mb-2{% if form.username.errors %} is-invalid{% endif %}" placeholder="{% trans 'Username' %}" required autofocus>
            <div class="invalid-feedback">
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% else %}
                    {% trans "Missing username" %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="email">{% trans 'Email' %}</label>
            <input type="email" id="email" name="email" class="form-control rounded mb-2{% if form.email.errors %} is-invalid{% endif %}" placeholder="{% trans 'Email' %}" required autofocus>
            <div class="invalid-feedback">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% else %}
                    {% trans "Invalid email" %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="password1">{% trans 'Password' %}</label>
            <input type="password" id="password1" name="password1" class="form-control rounded mb-2{% if form.password1.errors %} is-invalid{% endif %}" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% else %}
                    {% trans "Missing password" %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="password2">{% trans 'Confirm password' %}</label>
            <input type="password" id="password2" name="password2" class="form-control rounded{% if form.password2.errors %} is-invalid{% endif %}" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% else %}
                    {% trans "Missing password" %}
                {% endif %}
            </div>
        </div>
        <button class="btn btn-lg btn-primary btn-block my-1" type="submit">{% trans 'Register' %}</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'competition/formValidation.js' %}"></script>
{% endblock %}

competition/templates/competition/template.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'football/favicon.png' %}">

    <title>League generator</title>

    <link href="{% static 'bootstrap/v4/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'competition/style.css' %}" rel="stylesheet">

    <style>
        .navbar {
            background: url({% static 'competition/images/bg.jpg' %}) center center fixed;
            -webkit-background-size: 100%;
            -moz-background-size: 100%;
            -o-background-size: 100%;
            background-size: 100%;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <a class="navbar-brand" href="/"><img style="height: 30px" src="{% static 'football/images/football_icon.png' %}" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" />
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <div class="dropdown">
            {% if user.is_authenticated  %}
            <a href="{% url 'competition:users_leagues' %}" class="btn btn-outline-light" role="button">{% trans 'My leagues' %}</a>
            {% endif %}
            <button class="btn btn-outline-light dropdown-toggle" type="button" id="createLeagueButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans 'Create league' %}
            </button>
            <div class="dropdown-menu" aria-labelledby="createLeagueButton">
                <a class="dropdown-item" href="{% url 'football:create_league' %}">{% trans "Football" %}</a>
                <a class="dropdown-item" href="">{% trans "Hockey" %}</a>
                <a class="dropdown-item" href="">{% trans "Cross country" %}</a>
            </div>
        </div>
        <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url 'competition:search' %}">
            <input name="q" class="form-control mr-sm-2" type="text" placeholder="{% trans "Search" %}" aria-label="Search">
            <button class="btn btn-default my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
        </form>
        {% if user.is_authenticated  %}
            <a href="{% url 'competition:logout' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Logout' %}</a>
        {% else %}
            <a href="{% url 'competition:login' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Login' %}</a>
            <a href="{% url 'competition:register' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Register' %}</a>
        {% endif %}
    </div>
</nav>
<div id="banner" class="mb-3" style="visibility: hidden">{% block banner_text %}{% endblock %}</div>
<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.js"></script>
<script src="{% static 'bootstrap/v4/js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

competition/templates/competition/tournament_list.html
{% extends 'competition/template.html' %}
{% load i18n %}

{% load static %}
{% block content %}
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">{% trans 'Name' %}</th>
                <th scope="col">{% trans 'Type' %}</th>
            </tr>
        </thead>
        {% for tournament in object_list %}
            <tr>
                <td><a href="{% url 'football:tournament' tournament.ext_id %}">{{ tournament.name }}</a></td>
                <td>{% trans tournament.get_type_display %}</td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        <p>{% trans "No matching tournaments" %}</p>
    {% endif %}
{% endblock %}